export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_LOGIN_FAIL = 'AUTH_LOGIN_FAIL';
export const AUTH_LOGOUT_FAIL = 'AUTH_LOGOUT_FAIL';
export const AUTH_REGISTER_FAIL = 'AUTH_REGISTER_FAIL';
export const GET_MESSAGE_SUCCESS = 'GET_MESSAGE_SUCCESS';
export const GET_MESSAGE_FAIL = 'GET_MESSAGE_FAIL';
export const MESSAGE_UPDATE_SUCCESS = 'MESSAGE_UPDATE_SUCCESS';
export const MESSAGE_UPDATE_FAIL = 'MESSAGE_UPDATE_FAIL';
